name: plp
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  crop_your_image: ^2.0.0
  font_awesome_flutter: ^10.8.0
  mobile_scanner: ^6.0.6
  flutter_speed_dial: ^7.0.0
  qr_flutter: ^4.1.0
  new_version_plus: ^0.1.0
  flutter_launcher_icons: ^0.14.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/oldicon.png"
  

  

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
  
  fonts:
    - family: PhetsarathOT
      fonts:
        - asset: assets/PhetsarathOT.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
